caddy:
    env: ENC[AES256_GCM,data:SHE/hiYegax08PsVQXBk1s7OYEMpU8zsjOFKFbNyaSixgjjqiaP85m/Q0rX/iO1ASHhbstUUD+HXaWrg9XIGToKa7z6ZVpMST7Nx5JmZ3kHWlwtd,iv:rVWQWJp2Z40M9C4DDR5BWjVVvCEj1FrM9XH8/6uSrEo=,tag:70Pm4S/jJSGUYQIKSTrrvg==,type:str]
sops:
    age:
        - recipient: age16zt75n2yxu93j8ttdm4425cqjncd0f7eswha8cvzcs94vx2aedcq03t8k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK2ZudzJLQWN3U2N4TzFD
            QW9QQWsvSjZFY2trSnN0VkErQUV4ckJ3c1I4CjlBK1FJQWd4NWVtTTFOMTVsZ2pS
            THdrZXRPRlYwYkRUaVM5aXYrYmlaWkEKLS0tIHhDMU91YWhzQTZDeG8vSGpPVEVn
            N1cxdzdCZ1JjS3FxWW1aZFdZV1c1aVEK5/NylIbGYF9nm+cH0CP5c0JKPUSDDgx2
            mMkno5qRCrTxto7V9JNhsb3Ti3LaW1tPPgA8KHrDRdbyrdTDgzv+yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18klmmds75e9p8rfy9y99f2kvvjkvq8kptxs4cffkwqz6ljtjfvks649avv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRzA5M25kd0xsWmp2NnFk
            d1A0L2pQY0xURnpxL0E0bzh1NDQ1ZHVCa21RCk03M0JXL3VjekJqSzN1ck5heTBP
            QVZEUzZaTjlrZ2hNNHVyb2xITVpVRUUKLS0tIGtEK01EQ0xDRjE4S3ZJZVRWVHh0
            RFgvUUtiSVZrb3A4dDVUZ1J6QnAzRm8Ka+IxrsQCuV+vM6MaMUkln0WiGgf8YC2D
            SQCIiEZAkmeZDE6YEdwbO/LGT3rWvPlCum012GD8S2ZXlf6mOTFVcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15hrdghf736p7gm5tc6dtsd0nad94a9f67alp55hvagu7xtkesccs0hjruj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2NXaGlrZVpqb3lXczMw
            ZmhJZUIxejNSM0hhU1AwZ3BwYy9TaWlGOEFBCnZkcDRUdW04YzVTRjJSUlR6QjQw
            Lyt5d0RiSk9nZ2pyWTg0cEhOR002Q1kKLS0tIEhORGdKbXpnQ3d0QWV3L0NRTzJu
            aG5OUlZWbnMyRGZkRG4vbHlDQVEyL0kKLPN+Zx6sZeUETTgL4ZaraGh7lnYIXcLB
            G9bzpxuqvIyl4usMOd+5Dvxv62zA2KVUqyge5lJxNcT3RLxc5+OcVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T10:55:02Z"
    mac: ENC[AES256_GCM,data:h0UNlsnOgqWjyral3FLKUGADEpVnJM1F8gd5h3nZxsRbpUK22LWRPC1X6RFL3v6I6la74JHtHnWH8ezrhbQm843kiiDfeeiQ7CAzoCU4VtQdTmKKt6VDwmQ9nC92A3K6SCDO6wqB5GIbjHS2FfHOG7gtfhwaJ9KB0T5zn6oj8bY=,iv:JlV158CYMJnifsTZXgV74pp52HxmnU+lCwNaS5960YE=,tag:gX7xejVAKTNBHWp3hNOuVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
