caddy:
    env: ENC[AES256_GCM,data:8Yk0A00U03UHkSoMdMjpSO1sE5PoqXoWr2Sdf7pDnu2canl+nzbPpESvcXnGMPkA4wDlGiXAzv1B9MWA+3TNarQdJBiahU2STC7q1G5vI3InJeGB,iv:cZdDWz9Nke5xciSy48UqToM4ZGT/vF7wHL2UZ+I6oKE=,tag:53NdXG3keYx2S2k4mjjdEA==,type:str]
sops:
    age:
        - recipient: age16zt75n2yxu93j8ttdm4425cqjncd0f7eswha8cvzcs94vx2aedcq03t8k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK2ZudzJLQWN3U2N4TzFD
            QW9QQWsvSjZFY2trSnN0VkErQUV4ckJ3c1I4CjlBK1FJQWd4NWVtTTFOMTVsZ2pS
            THdrZXRPRlYwYkRUaVM5aXYrYmlaWkEKLS0tIHhDMU91YWhzQTZDeG8vSGpPVEVn
            N1cxdzdCZ1JjS3FxWW1aZFdZV1c1aVEK5/NylIbGYF9nm+cH0CP5c0JKPUSDDgx2
            mMkno5qRCrTxto7V9JNhsb3Ti3LaW1tPPgA8KHrDRdbyrdTDgzv+yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18klmmds75e9p8rfy9y99f2kvvjkvq8kptxs4cffkwqz6ljtjfvks649avv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRzA5M25kd0xsWmp2NnFk
            d1A0L2pQY0xURnpxL0E0bzh1NDQ1ZHVCa21RCk03M0JXL3VjekJqSzN1ck5heTBP
            QVZEUzZaTjlrZ2hNNHVyb2xITVpVRUUKLS0tIGtEK01EQ0xDRjE4S3ZJZVRWVHh0
            RFgvUUtiSVZrb3A4dDVUZ1J6QnAzRm8Ka+IxrsQCuV+vM6MaMUkln0WiGgf8YC2D
            SQCIiEZAkmeZDE6YEdwbO/LGT3rWvPlCum012GD8S2ZXlf6mOTFVcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15hrdghf736p7gm5tc6dtsd0nad94a9f67alp55hvagu7xtkesccs0hjruj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2NXaGlrZVpqb3lXczMw
            ZmhJZUIxejNSM0hhU1AwZ3BwYy9TaWlGOEFBCnZkcDRUdW04YzVTRjJSUlR6QjQw
            Lyt5d0RiSk9nZ2pyWTg0cEhOR002Q1kKLS0tIEhORGdKbXpnQ3d0QWV3L0NRTzJu
            aG5OUlZWbnMyRGZkRG4vbHlDQVEyL0kKLPN+Zx6sZeUETTgL4ZaraGh7lnYIXcLB
            G9bzpxuqvIyl4usMOd+5Dvxv62zA2KVUqyge5lJxNcT3RLxc5+OcVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T03:15:11Z"
    mac: ENC[AES256_GCM,data:faT+UJxNNDbTmD4eRKZVoaeTlvnz66yVF1rwrfL/bsB1jw1mw+qNXrzb/zQcN4XmLRu4eF0PGC+FGSiqUUg1BF5t/G9aBqf9o8KC9x0MuefDG3Yth7NL1pAFmqsxrtBem3lqqkl89eBl203zrER03gSrSYI7Zl2hMqcfF/iDweU=,iv:YvEvu5qvtXbmCufx+bDH/XiLb/iodbZOWEWoXzBC4ek=,tag:2zU1dv+O7Iu8N2C++GiX5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
